execute @s -9 ~ ~ scoreboard players set @s[dx=0] spacon_digit -9
execute @s -8 ~ ~ scoreboard players set @s[dx=0] spacon_digit -8
execute @s -7 ~ ~ scoreboard players set @s[dx=0] spacon_digit -7
execute @s -6 ~ ~ scoreboard players set @s[dx=0] spacon_digit -6
execute @s -5 ~ ~ scoreboard players set @s[dx=0] spacon_digit -5
execute @s -4 ~ ~ scoreboard players set @s[dx=0] spacon_digit -4
execute @s -3 ~ ~ scoreboard players set @s[dx=0] spacon_digit -3
execute @s -2 ~ ~ scoreboard players set @s[dx=0] spacon_digit -2
execute @s -1 ~ ~ scoreboard players set @s[dx=0] spacon_digit -1
execute @s 0 ~ ~ scoreboard players set @s[dx=0] spacon_digit 0
execute @s 1 ~ ~ scoreboard players set @s[dx=0] spacon_digit 1
execute @s 2 ~ ~ scoreboard players set @s[dx=0] spacon_digit 2
execute @s 3 ~ ~ scoreboard players set @s[dx=0] spacon_digit 3
execute @s 4 ~ ~ scoreboard players set @s[dx=0] spacon_digit 4
execute @s 5 ~ ~ scoreboard players set @s[dx=0] spacon_digit 5
execute @s 6 ~ ~ scoreboard players set @s[dx=0] spacon_digit 6
execute @s 7 ~ ~ scoreboard players set @s[dx=0] spacon_digit 7
execute @s 8 ~ ~ scoreboard players set @s[dx=0] spacon_digit 8
execute @s 9 ~ ~ scoreboard players set @s[dx=0] spacon_digit 9

scoreboard players operation @s spacon_x += @s spacon_digit