summon spacon:raycast ^ ^ ^
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^0.1
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^0.2
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^0.3
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^0.4
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^0.5
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^0.6
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^0.7
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^0.8
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^0.9
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^1
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^1.1
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^1.2
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^1.3
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^1.4
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^1.5
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^1.6
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^1.7
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^1.8
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^1.9
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^2
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^2.1
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^2.2
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^2.3
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^2.4
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^2.5
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^2.6
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^2.7
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^2.8
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^2.9
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^3
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^3.1
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^3.2
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^3.3
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^3.4
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^3.5
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^3.6
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^3.7
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^3.8
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^3.9
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^4
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^4.1
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^4.2
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^4.3
execute @e[type=spacon:raycast] ~ ~ ~ function spaco4n/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^4.4
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^4.5
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^4.6
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^4.7
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^4.8
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^4.9
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check
execute @s ~ ~1.7 ~ tp @e[type=spacon:raycast] ^ ^ ^5
execute @e[type=spacon:raycast] ~ ~ ~ function spacon/misc/raycast_collision_check