tp @s[scores={spacon_digit_1=-9}] ~-9 ~ ~
tp @s[scores={spacon_digit_1=-8}] ~-8 ~ ~
tp @s[scores={spacon_digit_1=-7}] ~-7 ~ ~
tp @s[scores={spacon_digit_1=-6}] ~-6 ~ ~
tp @s[scores={spacon_digit_1=-5}] ~-5 ~ ~
tp @s[scores={spacon_digit_1=-4}] ~-4 ~ ~
tp @s[scores={spacon_digit_1=-3}] ~-3 ~ ~
tp @s[scores={spacon_digit_1=-2}] ~-2 ~ ~
tp @s[scores={spacon_digit_1=-1}] ~-1 ~ ~
tp @s[scores={spacon_digit_1=0}] ~ ~ ~
tp @s[scores={spacon_digit_1=1}] ~1 ~ ~
tp @s[scores={spacon_digit_1=2}] ~2 ~ ~
tp @s[scores={spacon_digit_1=3}] ~3 ~ ~
tp @s[scores={spacon_digit_1=4}] ~4 ~ ~
tp @s[scores={spacon_digit_1=5}] ~5 ~ ~
tp @s[scores={spacon_digit_1=6}] ~6 ~ ~
tp @s[scores={spacon_digit_1=7}] ~7 ~ ~
tp @s[scores={spacon_digit_1=8}] ~8 ~ ~
tp @s[scores={spacon_digit_1=9}] ~9 ~ ~