tp @s[scores={spacon_digit_2=-9}] ~-90 ~ ~
tp @s[scores={spacon_digit_2=-8}] ~-80 ~ ~
tp @s[scores={spacon_digit_2=-7}] ~-70 ~ ~
tp @s[scores={spacon_digit_2=-6}] ~-60 ~ ~
tp @s[scores={spacon_digit_2=-5}] ~-50 ~ ~
tp @s[scores={spacon_digit_2=-4}] ~-40 ~ ~
tp @s[scores={spacon_digit_2=-3}] ~-30 ~ ~
tp @s[scores={spacon_digit_2=-2}] ~-20 ~ ~
tp @s[scores={spacon_digit_2=-1}] ~-10 ~ ~
tp @s[scores={spacon_digit_2=0}] ~ ~ ~
tp @s[scores={spacon_digit_2=1}] ~10 ~ ~
tp @s[scores={spacon_digit_2=2}] ~20 ~ ~
tp @s[scores={spacon_digit_2=3}] ~30 ~ ~
tp @s[scores={spacon_digit_2=4}] ~40 ~ ~
tp @s[scores={spacon_digit_2=5}] ~50 ~ ~
tp @s[scores={spacon_digit_2=6}] ~60 ~ ~
tp @s[scores={spacon_digit_2=7}] ~70 ~ ~
tp @s[scores={spacon_digit_2=8}] ~80 ~ ~
tp @s[scores={spacon_digit_2=9}] ~90 ~ ~